### ISSUE TITLE
unable to run mean_na function in windows R installation

### ISSUE THREAD

**Issue by friedrichknuth** [friedrichknuth/fish_seascape#3]
Hi Dan - I installed R on a more powerful windows machine in the lab. Same (by now old) version as on my mac 3.1.2. When I run the function
```{r}
mean_na = function(x) mean(x, na.rm=T)
depth_extract_mean = extract(depth, grids_count$m1000, fun=mean_na)
```
I receive the following error
`Error in fun(res[[i]], na.rm = na.rm) : unused argument (na.rm = na.rm)`
I tried running
```{r}
depth_extract_mean = extract(depth, grids_count$m1000, fun=mean_na)
```
thinking `extract()` might be behaving the way we originally thought it would, but that then still spits out a bunch of na values.

Again, I made sure to have the same version of R installed, but that didn't do the trick. I can run the script on my mac over night, which worked for all grid_count values, but grid_all is way larger, since it will do the raster calculation within a polygon area for every single fish intersected with that polygon, effectively treating them all like individual polygons. 

One thought is that if we knew which fish are in a given polygon, we really would only have to calculate the raster value for that polygon once, and then populate it for every fish within the polygon. Not sure yet how to do this, but I will give it some thought.

**Comment by dmcglinn** [comment]
The key may be not what version of R you have installed but what version of raster you have installed. Run the following:
```
library(raster)
citation("raster")
```
that will tell you the version number you have installed. Maybe on your mac you have an older version.

**Comment by friedrichknuth** [comment]
I installed the older version of `raster` 2.3-24 ... same error. at this point I am using the same version of R and same version of `raster`. for now, i will try to run the script on my mac.

**Comment by friedrichknuth** [comment]
I just ran 
`depth_extract_mean = extract(depth, grids_count$m1000, fun=mean, na.rm=T)`

instead of
`mean_na = function(x) mean(x, na.rm=T)`
`depth_extract_mean = extract(depth, grids_count$m1000, fun=mean_na)`

and it worked!!!

note:
`depth_extract_mean = extract(depth, grids_count$m1000, fun=mean, na.rm=T)` without `na.rm=T` doesn't omit NA values, thus TRUE must not be set as default and must be specified.

Closing ticket.
